### ISSUE TITLE
No redirect to login page when secure pages are accessed unauthenticated

### ISSUE THREAD

**Issue by premdass** [auth0-samples/auth0-angularjs-samples#13]
When we hit the profile page (secure page) , without logging in, it is not redirecting to login page, instead JS error is thrown saying token is null

**Comment by chenkie** [comment]
It's intentional for that sample :) These samples present incremental feature additions for securing a whole application. There will be a sample up shortly called `04-Authorization` which will cover what you're looking for. In the meantime, check out [angular-jwt](https://github.com/auth0/angular-jwt) and, in particular, the instructions for adding [requiresLogin](https://github.com/auth0/angular-jwt#limiting-access-to-routes).

**Comment by chenkie** [comment]
Here's the sample: https://github.com/auth0-samples/auth0-angularjs-samples/tree/master/04-Authorization

**Comment by premdass** [comment]
Thanks for the quick turn around @chenkie . Will test it soon, and close the issue.

Btw, we are starting a new angular spa using auth0 with api auth, and i assume this project should be prefered than the old angular samples, which doesnt use newer options for api auth (OIDC) ?

**Comment by chenkie** [comment]
No prob :)

Yes that's correct! We recommend following OIDC as laid out in these samples and in the [quickstarts](https://auth0.com/docs/quickstart/spa/angularjs).
