### ISSUE TITLE
Deprecated express-jwt-authz in 04-authorization

### ISSUE THREAD

**Issue by paulioceano** [auth0-samples/auth0-angularjs-samples#25]
When running the sample for 04-authorization, during the "Ping" for "Call Private" in the server console I get the following deprecated message.

![error04](https://user-images.githubusercontent.com/15818783/31475880-4bf400ec-aed1-11e7-8ea8-34f34d37e72a.png)

AUTH-3812

**Comment by jimmyjames** [comment]
This error is coming from the `express-jwt-authz` package. Looks like it is fixed in version `2.0.0`.

@luisrudge any reason this sample can't be updated to use latest version of `express-jwt-authz` (this sample already uses Express 4, and when trying locally it seemed to work, but not sure if there are incompatibilities that I'm not aware of).
