### ISSUE TITLE
Trying to request profile/getUserInfo asynchronously in v10

### ISSUE THREAD

**Issue by alobban** [auth0-samples/auth0-angularjs-samples#3]
Here is my current setup after a couple days of determining auth0-lock 10.11.0 requires auth0.js:

          lock.on('authenticated', function (authResult) {
                store.set('id_token', authResult.idToken);
                lock.getProfile(authResult.idToken, function (error, profile) {
                    if (error) {
                        return console.log(error);
                    }
                    store.set('profile', profile);
                });
                authManager.authenticate();
                ...
            });

Since version 9, both token and profile were transmitted in the same request.

**Comment by chenkie** [comment]
Hi @alobban 

The `getProfile` method from previous versions of Lock has been replaced with `getUserInfo`. When passed on `access_token`, it will return information for the user. This is the implementation in the 03-User-Profile sample:

```js
var accessToken = localStorage.getItem('access_token');
lock.getUserInfo(accessToken, function(err, profile) {
  // handle profile
});
```

You will of course need an `access_token` to begin with. It comes in the `authResult` when you authenticate a user.

```js
lock.on('authenticated', function(authResult) {
  console.log(authResult); // accessToken will be a key here
  localStorage.setItem('access_token', authResult.accessToken);
}
```

From our other conversation, it sounds like you're looking for a way to delay rendering your profile view until the profile call completes and you have an object to work with. Can you outline the behavior you're looking for in more detail so I can provide the best answer?

Thanks

**Comment by alobban** [comment]
@chenkie,
So the behavior that I am exhibiting is that upon login, I receive the token and my home page is updated as an authenticated session but the profile information isn't rendered because the controller did not receive the profile information. Hence no name or profile image was rendered.
![screenshot from 2017-02-28 17-06-41](https://cloud.githubusercontent.com/assets/3998145/23438632/57aa98ba-fdd8-11e6-8c71-0251e51ceaaf.png)

Versus my workaround with $timeout to refresh the scope to get the desired outcome:
![screenshot from 2017-02-28 17-03-59](https://cloud.githubusercontent.com/assets/3998145/23438648/6a79d41a-fdd8-11e6-979d-09318431e927.png)

**Comment by chenkie** [comment]
Instead of a `$timeout` you can use `$q` to set up a promise. [This sample](https://github.com/auth0-samples/auth0-angularjs-sample/tree/master/04-User-Profile) shows how to do that. Essentially you want to set up a promise for your profile in your AuthService and then later get it out using the promise's `then` method in the spot that you need it. In this case it looks like that spot is the main route. 

Have a look specifically at the [AuthService](https://github.com/auth0-samples/auth0-angularjs-sample/blob/master/04-User-Profile/components/auth/auth.service.js#L14-L55) and the [home controller](https://github.com/auth0-samples/auth0-angularjs-sample/blob/master/04-User-Profile/components/home/home.controller.js#L17-L19) in the above sample to see how this is implemented.

**Comment by alobban** [comment]
Awesome, I was just researching Promises on youtube and how to handle them in Async Callbacks.
Thanks @chenkie 

https://www.youtube.com/watch?v=yswb4SkDoj0

**Comment by chenkie** [comment]
awesome :)

I'll close this for now but please let me know how it goes with your implementation.
